automation-hero:
  sorting:
    merge:
      chunk-size: ${EXTERNAL_MERGE_CHUNK_SIZE:100000}
  resources:
    input-file-path: ${INPUT_FILE:C:/priv치t/automation-hero/test_input_file_big.txt}
    output-file-path: ${OUTPUT_FILE:C:/priv치t/automation-hero/test_output_file.txt}
    temp-file-path: ${TEMP_OUTPUT_FILE:C:/priv치t/automation-hero/temp_output_file.txt}
    temp-folder-path: ${TEMP_OUTPUT_FOLDER:C:/priv치t/automation-hero/temp_output_folder}